name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the "main" branch

jobs:
  deploy:
    name: Deploy Project to Server
    runs-on: ubuntu-latest  # Runner environment provided by GitHub

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.5'  # Match Node.js version with your local environment

      # Step 3: Export Environment Variables
      - name: Export Environment Variables
        run: |
          echo "CONVEX_DEPLOYMENT=${{ secrets.CONVEX_DEPLOYMENT }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_CONVEX_URL=${{ secrets.NEXT_PUBLIC_CONVEX_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> $GITHUB_ENV
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> $GITHUB_ENV
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> $GITHUB_ENV

      # Step 4: Install Dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build Project
      - name: Build project
        run: npm run build  # Make sure this matches your build command (e.g., `next build`)

      # Step 6: Deploy to Server via SSH
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          source: ".,!node_modules"  # Transfer all files except node_modules
          target: "/var/www/alignometrix"  # Replace with your server project path

      # Step 7: Restart the Application on Server
      - name: Restart Application on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/alignometrix
            npm install --production
            pm2 restart alignometrix || pm2 start npm --name "alignometrix" -- start